version: '3.3'

services:
   mysql:
     restart: always
     image: mysql:5.6
     volumes:
       - /data/mysql-docker/data:/var/lib/mysql
     restart: always
     expose:
       - '3306'
     ports:
       - '3306:3306'
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: db
       MYSQL_USER: user1
       MYSQL_PASSWORD: password1
       MYSQL_ROOT_HOST: '0.0.0.0'
